### ISSUE TITLE
Thank you very much for your efforts, thank you! I found a mistake

### ISSUE THREAD

**Issue by QQ1273459693** [seep/JoltPhysicsUnity#3]
![image](https://github.com/seep/JoltPhysicsUnity/assets/71361736/c81dc338-f2b9-476f-9bcf-ed6406b33680)
Steps: The number is greater than 500 or so will collapse! Tested many times

**Comment by QQ1273459693** [comment]
![image](https://github.com/seep/JoltPhysicsUnity/assets/71361736/09209304-9f81-450e-8f7a-1d80f230e466)
Sorry, I missed the maximum value here. What is your future plan? jolt has been updated to version 5.0 as of today!

**Comment by QQ1273459693** [comment]
> ![图像](https://private-user-images.githubusercontent.com/71361736/320166476-09209304-9f81-450e-8f7a-1d80f230e466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjU2MTMsIm5iZiI6MTcxMjM2NTMxMywicGF0aCI6Ii83MTM2MTczNi8zMjAxNjY0NzYtMDkyMDkzMDQtOWY4MS00NTBlLThmN2EtMWQ4MGYyMzBlNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxMDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NTU1ZjY1MGI3NmNhMjFkODg0ZjY5MTgyYWY4NWQ5OTEwMjY5NzU2NDJmNDJmMGMwOTc5ZTM0MDQyYjgwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-Ghn9yyThSz6ien3Z-jXGjs9NeKDsyEmdT0cMwOhU4) 抱歉，我错过了这里的最大值。你未来的计划是什么？今天jolt已经更新到5.0版本了！

![{6F$8XDIRJMU(@ PUQ~E$3H](https://github.com/seep/JoltPhysicsUnity/assets/71361736/bbfe7792-f687-468c-a0d0-ebcc77291c72)
The number of frames dropped from around 500 FPS to 30 FPS, then reverted to 300FPS when the physical object stopped moving

**Comment by QQ1273459693** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/71361736/320166476-09209304-9f81-450e-8f7a-1d80f230e466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjU2MTMsIm5iZiI6MTcxMjM2NTMxMywicGF0aCI6Ii83MTM2MTczNi8zMjAxNjY0NzYtMDkyMDkzMDQtOWY4MS00NTBlLThmN2EtMWQ4MGYyMzBlNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxMDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NTU1ZjY1MGI3NmNhMjFkODg0ZjY5MTgyYWY4NWQ5OTEwMjY5NzU2NDJmNDJmMGMwOTc5ZTM0MDQyYjgwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-Ghn9yyThSz6ien3Z-jXGjs9NeKDsyEmdT0cMwOhU4)抱歉，我错过了这里的顶峰。你未来的计划是什么？今天摇晃已经更新到5.0版本了！
> 
> ![{6F$8XDIRJMU(@PUQ~E$3H](https://private-user-images.githubusercontent.com/71361736/320167492-bbfe7792-f687-468c-a0d0-ebcc77291c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjU2OTYsIm5iZiI6MTcxMjM2NTM5NiwicGF0aCI6Ii83MTM2MTczNi8zMjAxNjc0OTItYmJmZTc3OTItZjY4Ny00NjhjLWEwZDAtZWJjYzc3MjkxYzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxMDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYmNjMDVlOGRmZjA0NmM5MjZhNGQ1MDRhMjc3NTdjOWE3OGRlMDU4OGZlODc2YTk0MWFhYTBlZTU3NzMyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7--AHPkdRGmjFEnbNTthLiP1ZJK9_sWNIJ0yM1nyNzg) 帧数从 500 FPS 左右下降到 30 FPS，然后当物理对象停止移动时恢复到 300 FPS

![7 (}_G`%C)`8EM% VWJQ83U](https://github.com/seep/JoltPhysicsUnity/assets/71361736/bbe27634-0e55-4d35-9570-fe1797361716)

**Comment by seep** [comment]
With 0f86361, the native libs are compiled from a Jolt 5.0 commit.

Regarding the crash, I think I need more information. Have you tried running a native Jolt simulation with 500 collision steps per iteration? That number seems really high.

**Comment by QQ1273459693** [comment]
> 使用[0f86361](https://github.com/seep/JoltPhysicsUnity/commit/0f8636136e90bffca19755b69bc053cf24b23d31)，本机库是从 Jolt 5.0 提交编译的。
> 
> 关于坠机事件，我想我需要更多信息。您是否尝试过运行每次迭代 500 个碰撞步骤的本机 Jolt 模拟？这个数字看起来确实很高。

Around 700 units will be generated above the performance will drop very seriously, all rigid body rest when the frame number becomes high, you can try to generate more than 700 units
