### ISSUE TITLE
Improve samples in unity package manager

### ISSUE THREAD

**Issue by shiena** [seep/JoltPhysicsUnity#5]
You can install samples from the package manager by following the steps below.

- move Jolt.Samples to Jolt.Samples~
- move Jolt.Samples.Editor to Jolt.Samples.Editor~
- apply patch

```diff
diff --git a/package.json b/package.json
index 5c56d54..0ee58d2 100644
--- a/package.json
+++ b/package.json
@@ -6,5 +6,15 @@
   "dependencies": {
     "com.unity.mathematics": "1.0.0",
     "com.unity.collections": "1.0.0"
-  }
+  },
+  "samples": [
+	  {
+		  "displayName": "Jolt.Samples",
+		  "path": "Jolt.Samples~"
+	  },
+	  {
+		  "displayName": "Jolt.Samples.Editor",
+		  "path": "Jolt.Samples.Editor~"
+	  }
+  ]
 }
```

Here is a screenshot of the package manager after applying the above.

![image](https://github.com/user-attachments/assets/7634a143-6697-43a2-9842-4941983d9c2e)

**Comment by shiena** [comment]
Of the assets provided as upm, scene files cannot be opened directly.
Therefore, it is necessary to use a tilde to create a hidden folder and import it as a sample.

https://discussions.unity.com/t/cant-save-scenes-into-packages-cant-load-scenes-from-packages/723362
https://discussions.unity.com/t/samples-in-packages-manual-setup/730846

**Comment by seep** [comment]
Good suggestion, tackled in eebb4c45b9cc66d46e6d931dcb169c2b31b2dd8a.
